- name: Provision Playbook
  hosts: desktop
  gather_facts: true
  vars_files:
    - vars/packages-apt.yaml
    - vars/remote-non-repo-debs.yaml
  tasks:
  - name: Ensure Distro apt repo packages are up to date
    apt:
      name: "*"
      state: latest
      force_apt_get: yes
    tags:
      - pkg_update
  - name: Ensure Debian apt Packages are Present
    apt:
      update_cache: yes
      name: "{{ apt_packages}}"
      state: present
  - name: Ensure Remote Non-Repo Packages are up to Date
    apt:
      deb: "{{ item }}"
      state: present
    loop: "{{ remote_non_repo_debs }}"

  - name: Ensure avahi-daemon (for automatic printer detection) is enable and started
    systemd:
      name: avahi-daemon
      enabled: yes
      state: started

  - name: Ensure sshd is enable and started
    systemd:
      name: sshd
      enabled: yes
      state: started

- import_playbook: provision-common-desktop-roles.yaml

- name: Final Provision Step
  hosts: desktop
  gather_facts: true
  vars_files:
    - vars/packages-apt.yaml
  tasks:
  - name: Make sure alternative browsers are Absent
    apt:
      update_cache: yes
      name: "{{ apt_disallowed_browsers }}"
      state: absent  